// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	bytes "bytes"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// UploadImageByEmail mocks base method.
func (m *MockRepo) UploadImageByEmail(ctx context.Context, buffer *bytes.Buffer, filename string, filesize int64, mimeType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImageByEmail", ctx, buffer, filename, filesize, mimeType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImageByEmail indicates an expected call of UploadImageByEmail.
func (mr *MockRepoMockRecorder) UploadImageByEmail(ctx, buffer, filename, filesize, mimeType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImageByEmail", reflect.TypeOf((*MockRepo)(nil).UploadImageByEmail), ctx, buffer, filename, filesize, mimeType)
}
